services:
  apivenda:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_DB: apivendas
      POSTGRES_PASSWORD: docker
    ports:
      - 5432:5432

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379
